In [1]:
import torch
from torchvision.io import read_video, write_video

In [2]:
vid = read_video("../data/samoyed_3_69.mp4")

RuntimeError: File not found: ../data/samoyed_3_69.mp4

In [5]:
len(vid)

3

In [11]:
vid[0].shape

torch.Size([69, 480, 640, 3])

In [12]:
vid[0].dtype

torch.uint8

In [24]:
vid[0][0]

tensor([[[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [253, 253, 253],
         [253, 253, 253],
         [253, 253, 253]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [253, 253, 253],
         [253, 253, 253],
         [253, 253, 253]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [253, 253, 253],
         [253, 253, 253],
         [253, 253, 253]],

        ...,

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [253, 253, 253],
         [253, 253, 253],
         [253, 253, 253]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [253, 253, 253],
         [253, 253, 253],
         [253, 253, 253]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [253, 253, 253],
        

In [12]:
from PIL import Image

In [13]:
img = Image.open("../data/images/dog.jpg")

In [14]:
import torchvision.transforms.functional as FT

In [15]:
img_tensor = FT.to_tensor(img)

In [16]:
img_tensor.shape # C, H, W

torch.Size([3, 1213, 1546])

In [17]:
img_tensor.dtype

torch.float32

In [18]:
img_tensor[0]

tensor([[0.0510, 0.0667, 0.0588,  ..., 0.0745, 0.0784, 0.0706],
        [0.0627, 0.0706, 0.0588,  ..., 0.0745, 0.0902, 0.0824],
        [0.0667, 0.0706, 0.0667,  ..., 0.0667, 0.0902, 0.0863],
        ...,
        [0.4039, 0.2824, 0.2235,  ..., 0.2510, 0.3412, 0.4863],
        [0.4353, 0.3373, 0.2863,  ..., 0.2588, 0.2980, 0.3725],
        [0.3686, 0.2784, 0.2627,  ..., 0.2118, 0.2235, 0.2980]])

In [23]:
(255 * img_tensor.permute((1, 2, 0))).type(torch.uint8)


tensor([[[ 13,  30,  12],
         [ 17,  34,  18],
         [ 15,  29,  14],
         ...,
         [ 19,  31,  17],
         [ 20,  33,  23],
         [ 18,  31,  21]],

        [[ 16,  27,  19],
         [ 18,  29,  23],
         [ 15,  26,  20],
         ...,
         [ 19,  31,  11],
         [ 23,  35,  15],
         [ 21,  33,  13]],

        [[ 17,  23,  19],
         [ 18,  24,  20],
         [ 17,  23,  19],
         ...,
         [ 17,  29,   9],
         [ 23,  35,  15],
         [ 22,  34,  14]],

        ...,

        [[103, 124,  91],
         [ 72,  98,  63],
         [ 57,  88,  56],
         ...,
         [ 64,  94,  66],
         [ 87, 107,  72],
         [124, 135, 103]],

        [[111, 123,  99],
         [ 86, 100,  77],
         [ 73,  93,  68],
         ...,
         [ 66,  96,  68],
         [ 76,  91,  58],
         [ 95, 102,  71]],

        [[ 94, 106,  82],
         [ 71,  85,  62],
         [ 67,  87,  62],
         ...,
         [ 54,  84,  56],
        

In [3]:
vid = read_video("../data/videos/dog/3-69.mp4", output_format="TCHW")

/Users/dgcnz/development/research/overfitting-net/.venv/lib/python3.9/site-packages/torchvision/io/video.py:162: UserWarning: The pts_unit 'pts' gives wrong results. Please use pts_unit 'sec'.
  warnings.warn("The pts_unit 'pts' gives wrong results. Please use pts_unit 'sec'.")


In [5]:
for x, a in zip(vid[0], range(len(vid[0]))):
    print(a)
    print(x.shape)

tensor([[[ 20,  19,  18,  ...,  25,  20,  19],
         [ 18,  17,  17,  ...,  28,  19,  19],
         [ 12,  12,  13,  ...,  27,  22,  22],
         ...,
         [  9,  11,  13,  ..., 225, 225, 226],
         [  8,  10,  12,  ..., 226, 226, 228],
         [  8,  10,  12,  ..., 226, 228, 229]],

        [[ 28,  27,  26,  ...,  33,  34,  33],
         [ 26,  25,  25,  ...,  37,  33,  33],
         [ 20,  20,  22,  ...,  37,  32,  32],
         ...,
         [  5,   8,  12,  ..., 218, 219, 221],
         [  4,   6,  11,  ..., 219, 223, 224],
         [  4,   6,  11,  ..., 219, 224, 225]],

        [[ 24,  23,  22,  ...,  17,  13,  12],
         [ 22,  20,  20,  ...,  20,  12,  12],
         [ 16,  16,  17,  ...,  20,  12,  12],
         ...,
         [  2,   4,   9,  ..., 221, 219, 221],
         [  1,   3,   8,  ..., 222, 222, 223],
         [  1,   3,   8,  ..., 222, 223, 224]]], dtype=torch.uint8)


AttributeError: 'int' object has no attribute 'shape'

In [9]:
vid[0].shape

torch.Size([69, 3, 404, 514])

In [11]:
vid[0][0]/255.0

tensor([[[0.0784, 0.0745, 0.0706,  ..., 0.0980, 0.0784, 0.0745],
         [0.0706, 0.0667, 0.0667,  ..., 0.1098, 0.0745, 0.0745],
         [0.0471, 0.0471, 0.0510,  ..., 0.1059, 0.0863, 0.0863],
         ...,
         [0.0353, 0.0431, 0.0510,  ..., 0.8824, 0.8824, 0.8863],
         [0.0314, 0.0392, 0.0471,  ..., 0.8863, 0.8863, 0.8941],
         [0.0314, 0.0392, 0.0471,  ..., 0.8863, 0.8941, 0.8980]],

        [[0.1098, 0.1059, 0.1020,  ..., 0.1294, 0.1333, 0.1294],
         [0.1020, 0.0980, 0.0980,  ..., 0.1451, 0.1294, 0.1294],
         [0.0784, 0.0784, 0.0863,  ..., 0.1451, 0.1255, 0.1255],
         ...,
         [0.0196, 0.0314, 0.0471,  ..., 0.8549, 0.8588, 0.8667],
         [0.0157, 0.0235, 0.0431,  ..., 0.8588, 0.8745, 0.8784],
         [0.0157, 0.0235, 0.0431,  ..., 0.8588, 0.8784, 0.8824]],

        [[0.0941, 0.0902, 0.0863,  ..., 0.0667, 0.0510, 0.0471],
         [0.0863, 0.0784, 0.0784,  ..., 0.0784, 0.0471, 0.0471],
         [0.0627, 0.0627, 0.0667,  ..., 0.0784, 0.0471, 0.